; Mobo values

[MOBO-FAN-CPU]
Measure=Plugin
Plugin=HWiNFO.dll
HWiNFOSensorID=#MOBO-SID#
HWiNFOSensorInstance=#MOBO-SIN#
HWiNFOEntryId=#MOBO-FAN-CPU#
HWiNFOType=CurrentValue

[MOBO_FAN_CH1]
Measure=Plugin
Plugin=HWiNFO.dll
HWiNFOSensorID=#MOBO-SID#
HWiNFOSensorInstance=#MOBO-SIN#
HWiNFOEntryId=#MOBO-FAN-CH1#
HWiNFOType=CurrentValue

[MOBO_FAN_CH2]
Measure=Plugin
Plugin=HWiNFO.dll
HWiNFOSensorID=#MOBO-SID#
HWiNFOSensorInstance=#MOBO-SIN#
HWiNFOEntryId=#MOBO-FAN-CH2#
HWiNFOType=CurrentValue